### ISSUE TITLE
Pls fix warning

### ISSUE THREAD

**Issue by Wojtechnology** [Zubdano/zql#6]
When you do shit like `events.map` the top level div or whatever tag needs the `key` property, or else you get this warning:
![image](https://user-images.githubusercontent.com/6377160/32701962-1dd26b32-c7ad-11e7-898d-c0878d1111c3.png)

**Comment by pranavanand** [comment]
Done in https://github.com/Zubdano/zql/commit/679cd9d95e2b6aefb06025992b0e13540fc678b1
